# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8705a6d2cff3c0571be3055cc16beb21bd662d168e30d7d641f9272f158b9826f491b55e5b52bc4644ee1b1ad35a3ffe9c30fd434076b8953b294141a720afcb

test:
  secret_key_base: 544cfee6feda74f331f01210c84bb4753f0ca0cec1e3e5cf6f1d7242da481d287557073aeee005a412db25495b8943dfb6a7ffc2669a2ccf8666ff9469ef30ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
